### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by contractorwolf**
add AWS Cloud Practitioner Certification Trainer to Coding and Dev category

### CODE REVIEW

**Comment by Anil-matcha** [comment]
Please fix the merge conflicts and resubmit

**Comment by contractorwolf** [comment]
done

**Comment by contractorwolf** [comment]
do I need to resubmit? I am not used to open source and working in projects that i dont have permissions on, thx

**Comment by Anil-matcha** [comment]
@contractorwolf Merged your changes

**Pull request merged**
